### ISSUE TITLE
ldapcontacts not working at all

### ISSUE THREAD

**Issue by moutzl** [KircheNeuenburg/ldapcontacts#15] opened 2017-11-10 11:51 UTC
Nov 10 13:49:39 nextcloud apache2[14822]: {PHP} syntax error, unexpected '>' at /var/www/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#274

**Comment by alexhor** [comment] 2017-11-10 12:01
which php version are you using?
The problem is caused by the "spaceship operator" which was introduced in php7

**Comment by moutzl** [comment] 2017-11-10 12:33
okay, I have PHP Version => 5.6.30-0+deb8u1. 
I can try to upgrade, but question is, what everything will php 7.x broke ;)

**Comment by moutzl** [comment] 2017-11-10 13:48
ok, with php7 I dont see contacts. Maybe something in the ldap settings?

Nov 10 15:44:22 nextcloud ownCloud[1073]: {PHP} ldap_search(): Search: No such object at /var/www/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#224
Nov 10 15:44:22 nextcloud ownCloud[1073]: {PHP} ldap_get_entries() expects parameter 2 to be resource, boolean given at /var/www/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#226
Nov 10 15:44:22 nextcloud ownCloud[1073]: {PHP} Invalid argument supplied for foreach() at /var/www/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#234

**Comment by alexhor** [comment] 2017-11-11 18:44
Are your ldap settings in Nextcloud correct? Can access your nextcloud with ldap user credentials?

**Comment by moutzl** [comment] 2017-11-12 10:35
yes of course. login/groups etc are working fine.


| hasMemberOfFilterSupport      | 1                                                |
| hasPagedResultSupport         |                                                  |
| homeFolderNamingRule          |                                                  |
| lastJpegPhotoLookup           | 0                                                |
| ldapAgentName                 | ldapNextcloud@xxxxxxxxxxx.org                       |
| ldapAgentPassword             | ***                                              |
| ldapAttributesForGroupSearch  |                                                  |
| ldapAttributesForUserSearch   |                                                  |
| ldapBackupHost                | 172.16.1.2                                       |
| ldapBackupPort                | 689                                              |
| ldapBase                      | dc=xxxxxx,dc=org                               |
| ldapBaseGroups                | dc=xxxxxxxxx,dc=org                               |
| ldapBaseUsers                 | dc=xxxxxxxxxxx,dc=org                               |
| ldapCacheTTL                  | 600                                              |
| ldapConfigurationActive       | 1                                                |
| ldapDefaultPPolicyDN          |                                                  |
| ldapDynamicGroupMemberURL     |                                                  |
| ldapEmailAttribute            | mail                                             |
| ldapExperiencedAdmin          | 0                                                |
| ldapExpertUUIDGroupAttr       |                                                  |
| ldapExpertUUIDUserAttr        |                                                  |
| ldapExpertUsernameAttr        |                                                  |
| ldapGidNumber                 | gidNumber                                        |
| ldapGroupDisplayName          | cn                                               |
| ldapGroupFilter               | (&(mailNickname=*)(objectCategory=group))        |
| ldapGroupFilterGroups         |                                                  |
| ldapGroupFilterMode           | 1                                                |
| ldapGroupFilterObjectclass    | group                                            |
| ldapGroupMemberAssocAttr      | member                                           |
| ldapHost                      | 172.16.1.1                                       |
| ldapIgnoreNamingRules         |                                                  |
| ldapLoginFilter               | (&(&(|(objectclass=user)))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                  |
| ldapLoginFilterEmail          | 0                                                |
| ldapLoginFilterMode           | 0                                                |
| ldapLoginFilterUsername       | 1                                                |
| ldapNestedGroups              | 0                                                |
| ldapOverrideMainServer        |                                                  |
| ldapPagingSize                | 500                                              |
| ldapPort                      | 389                                              |
| ldapQuotaAttribute            |                                                  |
| ldapQuotaDefault              |                                                  |
| ldapTLS                       | 0                                                |
| ldapUserDisplayName           | displayName                                      |
| ldapUserDisplayName2          |                                                  |
| ldapUserFilter                | (&(|(objectclass=user)))                         |
| ldapUserFilterGroups          |                                                  |
| ldapUserFilterMode            | 1                                                |
| ldapUserFilterObjectclass     | user                                             |
| ldapUuidGroupAttribute        | auto                                             |
| ldapUuidUserAttribute         | auto                                             |
| turnOffCertCheck              | 0                                                |
| turnOnPasswordChange          | 0         l

**Comment by alexhor** [comment] 2018-01-30 09:49
I have been inactive for a while, sorry.
In the current version, this app needs quiet specific LDAP attributes and object types provieded.
In v1.1 this will be gone an probably fix your error.

**Comment by alexhor** [comment] 2018-02-09 13:08
ok, the newest version is now available in the app store.
I hope this fixes your error.

**Comment by moutzl** [comment] 2018-02-11 11:16
Hi, now the cloud crash completely

{index} Exception: {"Exception":"TypeError","Message":"Argument 5 passed to OCA\\User_LDAP\\Access::__construct() must implement interface OCP\\IConfig, none given, called in \/var\/www\/nextcloud\/apps\/ldapcontacts\/lib\/Controller\/ContactController.php on line 122","Code":0,"Trace":"#0 \/var\/www\/nextcloud\/apps\/ldapcontacts\/lib\/Controller\/ContactController.php(122): OCA\\User_LDAP\\Access->__construct(Object(OCA\\User_LDAP\\Connection), Object(OCA\\User_LDAP\\LDAP), Object(OCA\\User_LDAP\\User\\Manager), Object(OCA\\User_LDAP\\Helper))\n#1 \/var\/www\/nextcloud\/apps\/ldapcontacts\/lib\/Controller\/ContactController.php(84): OCA\\LdapContacts\\Controller\\ContactController->load_config(Object(OCA\\User_LDAP\\User\\Manager), Object(OCA\\User_LDAP\\Helper), Object(OCA\\User_LDAP\\Mapping\\UserMapping), Object(OCA\\User_LDAP\\Mapping\\GroupMapping))\n#2 [internal function]: OCA\\LdapContacts\\Controller\\ContactController->__construct('ldapcontacts', Object(OC\\AppFramework\\Http\\Request), Object(OC\\AllConfig), Object(OCA\\LdapContacts\\Controller\\SettingsController), '59A9F727-1DAA-4...', Object(OCA\\User_LDAP\\User\\Manager), Object(OCA\\User_LDAP\\Helper), Object(OCA\\User_LDAP\\Mapping\\UserMapping), Object(OCA\\User_LDAP\\Mapping\\GroupMapping), Object(OC\\DB\\Connection))\n#3 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php(80): ReflectionClass->newInstanceArgs(Array)\n#4 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php(97): OC\\AppFramework\\Utility\\SimpleContainer->buildClass(Object(ReflectionClass))\n#5 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php(118): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCA\\\\LdapContact...')\n#6 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php(467): OC\\AppFramework\\Utility\\SimpleContainer->query('OCA\\\\LdapContact...')\n#7 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php(438): OC\\AppFramework\\DependencyInjection\\DIContainer->queryNoFallback('OCA\\\\LdapContact...')\n#8 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php(164): OC\\AppFramework\\DependencyInjection\\DIContainer->query('OCA\\\\LdapContact...')\n#9 \/var\/www\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php(109): OC\\AppFramework\\Utility\\SimpleContainer->OC\\AppFramework\\Utility\\{closure}(*** sensitive parameters replaced ***)\n#10 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php(116): Pimple\\Container->offsetGet('ContactControll...')\n#11 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php(460): OC\\AppFramework\\Utility\\SimpleContainer->query('ContactControll...')\n#12 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php(438): OC\\AppFramework\\DependencyInjection\\DIContainer->queryNoFallback('ContactControll...')\n#13 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(92): OC\\AppFramework\\DependencyInjection\\DIContainer->query('ContactControll...')\n#14 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('ContactControll...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#15 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#16 \/var\/www\/nextcloud\/lib\/private\/Route\/Router.php(297): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#17 \/var\/www\/nextcloud\/lib\/base.php(998): OC\\Route\\Router->match('\/apps\/ldapconta...')\n#18 \/var\/www\/nextcloud\/index.php(37): OC::handleRequest()\n#19 {main}","File":"\/var\/www\/nextcloud\/apps\/user_ldap\/lib\/Access.php","Line":99}

**Comment by alexhor** [comment] 2018-02-11 15:08
fixed with https://github.com/KircheNeuenburg/ldapcontacts/commit/5c8903b22f9a5173cced5d370e900007792d0093

**Comment by moutzl** [comment] 2018-02-11 19:13
now its still loading with:

 {PHP} ldap_search(): Search: No such object at /var/www/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#247

**Comment by alexhor** [comment] 2018-02-19 12:52
which version of the app are you using?
the function that is causing you problems isn't in that given position in the newest version.
Maybe try to delete and redownload the app.

**Comment by moutzl** [comment] 2018-02-19 16:06
deleted / reinstalled


Feb 19 18:06:03 nextcloud ownCloud[27011]: {PHP} ldap_search(): Search: No such object at /var/www/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#251
Feb 19 18:06:03 nextcloud ownCloud[27011]: {PHP} ldap_list(): Search: No such object at /var/www/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#354
Feb 19 18:06:03 nextcloud ownCloud[27011]: {PHP} ldap_get_entries() expects parameter 2 to be resource, boolean given at /var/www/nextcloud/apps/ldapcontacts/lib/Controller/ContactController.php#355

**Comment by alexhor** [comment] 2018-02-19 16:58
go to "Settings > LDAP / AD Integration > LDAP Contacts" and make sure all LDAP Attributes listed there exist on your LDAP server and otherwise modify them to fit your installation.

**Comment by j0hng0gu** [comment] 2018-02-22 09:19
Hi,

Since upgraded to NC13.0 LDAP Contacts doesn't work anymore. Does not display any contact.
And the errors from nextcloud.log is:
"Undefined index: entryuuid at /var/www/html/apps/ldapcontacts/lib/Controller/ContactController.php#470"
"Undefined index: entryuuid at /var/www/html/apps/ldapcontacts/lib/Controller/ContactController.php#471"

Environment:
CentOS 7.4
Apache 2.4.6
mysql 5.5.56
php 7.1.14

Integration with MS AD work fine, but not LDAP Contacts. In NC v.12.04 was working.

Any ideas what could be the problem?
Many thanks!

**Closed** 2020-01-08 16:11 UTC
Labels: bug
